# Copyright (c) 2023 Rafael F.M. & Reinaldo
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT
import httpx
import pytest


@pytest.fixture
def mock_articles_stats_response() -> httpx.Response:
    data = {
        "items": [
            {
                "id": "abcde",
                "collectionId": "yj5hrb87l3zixoo",
                "collectionName": "articles_stats",
                "title": "test",
                "description": "test",
                "user": "RELATION_RECORD_ID",
                "author_name": "test",
                "author_username": "test",
                "author_avatar": "filename.jpg",
                "document": "filename.jpg",
                "tags": ["RELATION_RECORD_ID"],
                "visibility": "public",
                "likes": 123,
                "views": 123,
                "latest_views": 123,
                "created": "2021-10-01 00:00:00.02Z",
                "updated": "2021-10-02 12:34:56.02Z",
                "expand": ["example_expand"],
            },
            {
                "id": "fghij",
                "collectionId": "yj5hrb87l3zixoo",
                "collectionName": "articles_stats",
                "title": "another test",
                "description": "another test",
                "user": "ANOTHER_RELATION_RECORD_ID",
                "author_name": "another test",
                "author_username": "another test",
                "author_avatar": "another_filename.jpg",
                "document": "another_filename.jpg",
                "tags": ["ANOTHER_RELATION_RECORD_ID"],
                "visibility": "private",
                "likes": 456,
                "views": 456,
                "latest_views": 456,
                "created": "2021-10-03 00:00:00.02Z",
                "updated": "2021-10-04 12:34:56.02Z",
                "expand": ["example_expand_2"],
            },
            {
                "id": "ijklm",
                "collectionId": "yj5hrb87l3zixoo",
                "collectionName": "articles_stats",
                "title": "third test",
                "description": "third test",
                "user": "THIRD_RELATION_RECORD_ID",
                "author_name": "third test",
                "author_username": "third test",
                "author_avatar": "third_filename.jpg",
                "document": "third_filename.jpg",
                "tags": ["THIRD_RELATION_RECORD_ID"],
                "visibility": "public",
                "likes": 789,
                "views": 789,
                "latest_views": 789,
                "created": "2021-10-05 00:00:00.02Z",
                "updated": "2021-10-06 12:34:56.02Z",
                "expand": ["example_expand_3"],
            },
            {
                "id": "nopqr",
                "collectionId": "yj5hrb87l3zixoo",
                "collectionName": "articles_stats",
                "title": "fourth test",
                "description": "fourth test",
                "user": "FOURTH_RELATION_RECORD_ID",
                "author_name": "fourth test",
                "author_username": "fourth test",
                "author_avatar": "fourth_filename.jpg",
                "document": "fourth_filename.jpg",
                "tags": ["FOURTH_RELATION_RECORD_ID"],
                "visibility": "private",
                "likes": 101,
                "views": 101,
                "latest_views": 101,
                "created": "2021-10-07 00:00:00.02Z",
                "updated": "2021-10-08 12:34:56.02Z",
                "expand": ["example_expand_4"],
            },
            # Add more items as needed
        ],
        "page": 1,
        "perPage": 4,
        "totalPages": 1,
        "totalItems": 4,
    }

    return httpx.Response(json=data, status_code=200)


@pytest.fixture
def mock_trending_response() -> httpx.Response:
    data = {
        "items": [
            {
                "id": "ijklm",
                "collectionId": "yj5hrb87l3zixoo",
                "collectionName": "articles_stats",
                "title": "third test",
                "description": "third test",
                "user": "THIRD_RELATION_RECORD_ID",
                "author_name": "third test",
                "author_username": "third test",
                "author_avatar": "third_filename.jpg",
                "document": "third_filename.jpg",
                "tags": ["THIRD_RELATION_RECORD_ID"],
                "visibility": "public",
                "likes": 789,
                "views": 789,
                "latest_views": 789,
                "created": "2021-10-05 00:00:00.02Z",
                "updated": "2021-10-06 12:34:56.02Z",
                "expand": ["example_expand_3"],
            },
            {
                "id": "fghij",
                "collectionId": "yj5hrb87l3zixoo",
                "collectionName": "articles_stats",
                "title": "another test",
                "description": "another test",
                "user": "ANOTHER_RELATION_RECORD_ID",
                "author_name": "another test",
                "author_username": "another test",
                "author_avatar": "another_filename.jpg",
                "document": "another_filename.jpg",
                "tags": ["ANOTHER_RELATION_RECORD_ID"],
                "visibility": "private",
                "likes": 456,
                "views": 456,
                "latest_views": 456,
                "created": "2021-10-03 00:00:00.02Z",
                "updated": "2021-10-04 12:34:56.02Z",
                "expand": ["example_expand_2"],
            },
            {
                "id": "abcde",
                "collectionId": "yj5hrb87l3zixoo",
                "collectionName": "articles_stats",
                "title": "test",
                "description": "test",
                "user": "RELATION_RECORD_ID",
                "author_name": "test",
                "author_username": "test",
                "author_avatar": "filename.jpg",
                "document": "filename.jpg",
                "tags": ["RELATION_RECORD_ID"],
                "visibility": "public",
                "likes": 123,
                "views": 123,
                "latest_views": 123,
                "created": "2021-10-01 00:00:00.02Z",
                "updated": "2021-10-02 12:34:56.02Z",
                "expand": ["example_expand"],
            },
            {
                "id": "nopqr",
                "collectionId": "yj5hrb87l3zixoo",
                "collectionName": "articles_stats",
                "title": "fourth test",
                "description": "fourth test",
                "user": "FOURTH_RELATION_RECORD_ID",
                "author_name": "fourth test",
                "author_username": "fourth test",
                "author_avatar": "fourth_filename.jpg",
                "document": "fourth_filename.jpg",
                "tags": ["FOURTH_RELATION_RECORD_ID"],
                "visibility": "private",
                "likes": 101,
                "views": 101,
                "latest_views": 101,
                "created": "2021-10-07 00:00:00.02Z",
                "updated": "2021-10-08 12:34:56.02Z",
                "expand": ["example_expand_4"],
            },
            # Add more items as needed
        ],
        "page": 1,
        "perPage": 4,
        "totalPages": 1,
        "totalItems": 4,
    }

    return httpx.Response(json=data, status_code=200)
