name: Build Documentation
on:
    push:
        branches:
            - main
        paths:
            - 'docs/**' # Only trigger when files in the "/docs" directory change
            - 'mkdocs.yml'

permissions:
    contents: write
jobs:
    doc-build:
        env:
            ENABLE_PDF_EXPORT: 1
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.11.x
            - name: Install dependencies
              run: pip install -r docs/requirements.txt
            - uses: actions/cache@v2
              with:
                  key: ${{ github.ref }}
                  path: .cache
            - name: Build documentation
              run: |
                  mkdocs build
            - name: Deploy
              run: mkdocs gh-deploy --force
