# Copyright (c) 2023 Rafael F.M. & Reinaldo
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Test Python

on:
    pull_request:
        types:
            - opened
            - synchronize
            - edited
        branches:
            - release
            - main

jobs:
    test-python:
        runs-on: ubuntu-latest
        # env:
        #     ACTIONS_STEP_DEBUG: true
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11.x'
            - name: Install app dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Install testing dependencies
              run: |
                  pip install -r tests/requirements.txt
            - name: Test with pytest
              run: |
                  pytest -v -s ./tests/
